figure;
plot(x, sin(x), 'b', 'LineWidth', 2);

btn = uicontrol('Style','pushbutton',...
    'String','Change Color',...
    'Position',[20 20 100 40],...
    'Callback', @(src,event) set(gca,'Color','y'));
